//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace soa_01.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://websrv.cs.fsu.edu/~engelen/calc.wsdl", ConfigurationName="CalculatorService.calcPortType")]
    public interface calcPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:calc) of message addRequest does not match the default value (http://websrv.cs.fsu.edu/~engelen/calc.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        soa_01.CalculatorService.addResponse add(soa_01.CalculatorService.addRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:calc) of message subRequest does not match the default value (http://websrv.cs.fsu.edu/~engelen/calc.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        soa_01.CalculatorService.subResponse sub(soa_01.CalculatorService.subRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:calc) of message mulRequest does not match the default value (http://websrv.cs.fsu.edu/~engelen/calc.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        soa_01.CalculatorService.mulResponse mul(soa_01.CalculatorService.mulRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:calc) of message divRequest does not match the default value (http://websrv.cs.fsu.edu/~engelen/calc.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        soa_01.CalculatorService.divResponse div(soa_01.CalculatorService.divRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (urn:calc) of message powRequest does not match the default value (http://websrv.cs.fsu.edu/~engelen/calc.wsdl)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        soa_01.CalculatorService.powResponse pow(soa_01.CalculatorService.powRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class addRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public addRequest() {
        }
        
        public addRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class addResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public addResponse() {
        }
        
        public addResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sub", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class subRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public subRequest() {
        }
        
        public subRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class subResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public subResponse() {
        }
        
        public subResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mul", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class mulRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public mulRequest() {
        }
        
        public mulRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mulResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class mulResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public mulResponse() {
        }
        
        public mulResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="div", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class divRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public divRequest() {
        }
        
        public divRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class divResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public divResponse() {
        }
        
        public divResponse(double result) {
            this.result = result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pow", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class powRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double a;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double b;
        
        public powRequest() {
        }
        
        public powRequest(double a, double b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="powResponse", WrapperNamespace="urn:calc", IsWrapped=true)]
    public partial class powResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double result;
        
        public powResponse() {
        }
        
        public powResponse(double result) {
            this.result = result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface calcPortTypeChannel : soa_01.CalculatorService.calcPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class calcPortTypeClient : System.ServiceModel.ClientBase<soa_01.CalculatorService.calcPortType>, soa_01.CalculatorService.calcPortType {
        
        public calcPortTypeClient() {
        }
        
        public calcPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public calcPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calcPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calcPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soa_01.CalculatorService.addResponse soa_01.CalculatorService.calcPortType.add(soa_01.CalculatorService.addRequest request) {
            return base.Channel.add(request);
        }
        
        public double add(double a, double b) {
            soa_01.CalculatorService.addRequest inValue = new soa_01.CalculatorService.addRequest();
            inValue.a = a;
            inValue.b = b;
            soa_01.CalculatorService.addResponse retVal = ((soa_01.CalculatorService.calcPortType)(this)).add(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soa_01.CalculatorService.subResponse soa_01.CalculatorService.calcPortType.sub(soa_01.CalculatorService.subRequest request) {
            return base.Channel.sub(request);
        }
        
        public double sub(double a, double b) {
            soa_01.CalculatorService.subRequest inValue = new soa_01.CalculatorService.subRequest();
            inValue.a = a;
            inValue.b = b;
            soa_01.CalculatorService.subResponse retVal = ((soa_01.CalculatorService.calcPortType)(this)).sub(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soa_01.CalculatorService.mulResponse soa_01.CalculatorService.calcPortType.mul(soa_01.CalculatorService.mulRequest request) {
            return base.Channel.mul(request);
        }
        
        public double mul(double a, double b) {
            soa_01.CalculatorService.mulRequest inValue = new soa_01.CalculatorService.mulRequest();
            inValue.a = a;
            inValue.b = b;
            soa_01.CalculatorService.mulResponse retVal = ((soa_01.CalculatorService.calcPortType)(this)).mul(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soa_01.CalculatorService.divResponse soa_01.CalculatorService.calcPortType.div(soa_01.CalculatorService.divRequest request) {
            return base.Channel.div(request);
        }
        
        public double div(double a, double b) {
            soa_01.CalculatorService.divRequest inValue = new soa_01.CalculatorService.divRequest();
            inValue.a = a;
            inValue.b = b;
            soa_01.CalculatorService.divResponse retVal = ((soa_01.CalculatorService.calcPortType)(this)).div(inValue);
            return retVal.result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        soa_01.CalculatorService.powResponse soa_01.CalculatorService.calcPortType.pow(soa_01.CalculatorService.powRequest request) {
            return base.Channel.pow(request);
        }
        
        public double pow(double a, double b) {
            soa_01.CalculatorService.powRequest inValue = new soa_01.CalculatorService.powRequest();
            inValue.a = a;
            inValue.b = b;
            soa_01.CalculatorService.powResponse retVal = ((soa_01.CalculatorService.calcPortType)(this)).pow(inValue);
            return retVal.result;
        }
    }
}
